[package]
name = "benchmarks"
version = "0.0.1"
edition = "2024"

[dependencies]
lang = { path = "../lang" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "vm_benchmarks"
harness = false
